name: pytorch
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py37_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1d=h7b6447c_3
  - pip=19.3.1=py37_0
  - python=3.7.6=h0371630_2
  - readline=7.0=h7b6447c_5
  - setuptools=44.0.0=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.9.0
    - alabaster==0.7.12
    - alphashape==1.1.0
    - appdirs==1.4.4
    - argh==0.26.2
    - arrow==1.1.1
    - astroid==2.3.3
    - astropy==4.0.1.post1
    - atomicwrites==1.3.0
    - attrs==19.3.0
    - autopep8==1.4.4
    - babel==2.8.0
    - backcall==0.1.0
    - binaryornot==0.4.4
    - black==20.8b1
    - bleach==3.1.0
    - cachetools==4.0.0
    - cffi==1.13.2
    - chardet==3.0.4
    - charset-normalizer==2.0.3
    - click==7.1.2
    - click-log==0.3.2
    - cloudpickle==1.2.2
    - cookiecutter==1.7.3
    - cryptography==2.8
    - cycler==0.10.0
    - cython==0.29.21
    - decorator==4.4.1
    - defusedxml==0.6.0
    - diff-match-patch==20181111
    - dipy==1.1.1
    - docutils==0.16
    - entrypoints==0.3
    - flake8==3.8.3
    - future==0.18.2
    - google-auth==1.10.0
    - google-auth-oauthlib==0.4.1
    - grpcio==1.26.0
    - h5py==2.10.0
    - hdbscan==0.8.26
    - helpdev==0.6.10
    - idna==2.8
    - imageio==2.6.1
    - imagesize==1.2.0
    - importlib-metadata==1.4.0
    - inflection==0.5.1
    - intervaltree==3.0.2
    - ipykernel==5.5.0
    - ipython==7.11.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - isort==4.3.21
    - jedi==0.17.2
    - jeepney==0.4.2
    - jinja2==2.10.3
    - jinja2-time==0.2.0
    - joblib==0.14.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==5.3.4
    - jupyter-console==6.1.0
    - jupyter-core==4.6.1
    - keyring==21.1.0
    - kiwisolver==1.1.0
    - lazy-object-proxy==1.4.3
    - markdown==3.1.1
    - markupsafe==1.1.1
    - matplotlib==3.1.2
    - mccabe==0.6.1
    - mistune==0.8.4
    - more-itertools==8.1.0
    - mypy-extensions==0.4.3
    - nbconvert==5.6.1
    - nbformat==5.0.3
    - networkx==2.4
    - nibabel==3.1.1
    - notebook==6.0.3
    - numpy==1.19.1
    - numpydoc==0.9.2
    - oauthlib==3.1.0
    - packaging==20.0
    - pandas==0.25.3
    - pandocfilters==1.4.2
    - parso==0.7.0
    - pathspec==0.8.1
    - pathtools==0.1.2
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - pillow==6.0.0
    - pluggy==0.13.1
    - poyo==0.5.0
    - prometheus-client==0.8.0
    - prompt-toolkit==3.0.2
    - protobuf==3.11.2
    - psutil==5.6.7
    - ptyprocess==0.6.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.6.0
    - pycparser==2.19
    - pydocstyle==5.0.2
    - pyflakes==2.2.0
    - pygments==2.5.2
    - pyklb==0.0.3.dev0
    - pylint==2.4.4
    - pyls-black==0.4.6
    - pyls-spyder==0.3.2
    - pyparsing==2.4.6
    - pyqt5==5.12.3
    - pyqt5-sip==12.7.0
    - pyqtwebengine==5.12.1
    - pyquaternion==0.9.9
    - pyrsistent==0.15.7
    - pyshtools==4.6.2
    - python-dateutil==2.8.1
    - python-jsonrpc-server==0.4.0
    - python-language-server==0.36.2
    - python-slugify==5.0.2
    - pytorch-lightning==0.7.1
    - pytz==2019.3
    - pywavelets==1.1.1
    - pyxdg==0.26
    - pyyaml==5.3
    - pyzmq==18.1.1
    - qdarkstyle==3.0.2
    - qstylizer==0.2.0
    - qtawesome==1.0.3
    - qtconsole==5.1.1
    - qtpy==1.9.0
    - regex==2020.11.13
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rope==0.16.0
    - rsa==4.0
    - rtree==0.9.7
    - scikit-image==0.16.2
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - secretstorage==3.1.2
    - send2trash==1.5.0
    - shapely==1.7.1
    - six==1.13.0
    - snowballstemmer==2.0.0
    - sortedcontainers==2.1.0
    - sphinx==2.3.1
    - sphinxcontrib-applehelp==1.0.1
    - sphinxcontrib-devhelp==1.0.1
    - sphinxcontrib-htmlhelp==1.0.2
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.2
    - sphinxcontrib-serializinghtml==1.1.3
    - spyder==5.0.5
    - spyder-kernels==2.0.5
    - tensorboard==2.1.0
    - terminado==0.8.3
    - test-tube==0.7.5
    - testpath==0.4.4
    - text-unidecode==1.3
    - textdistance==4.2.1
    - three-merge==0.1.1
    - tinycss2==1.1.0
    - toml==0.10.2
    - torch==1.3.1
    - torchvision==0.4.2
    - tornado==6.0.3
    - tqdm==4.35.0
    - traitlets==4.3.3
    - typed-ast==1.4.1
    - typing-extensions==3.7.4.3
    - ujson==3.2.0
    - urllib3==1.25.7
    - watchdog==1.0.2
    - wcwidth==0.1.8
    - webencodings==0.5.1
    - werkzeug==0.16.0
    - widgetsnbextension==3.5.1
    - wrapt==1.11.2
    - wurlitzer==2.0.0
    - xarray==0.16.0
    - yapf==0.29.0
    - zipp==1.0.0
prefix: /home/temp/eschweiler/miniconda3/envs/pytorch

