name: pytorch
channels:
  - defaults
dependencies:
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_1
  - openssl=1.1.1e=he774522_0
  - pip=20.0.2=py37_1
  - python=3.7.7=h60c2a47_0_cpython
  - setuptools=46.1.1=py37_0
  - sqlite=3.31.1=he774522_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wheel=0.34.2=py37_0
  - wincertstore=0.2=py37_0
  - pip:
    - absl-py==0.9.0
    - alabaster==0.7.12
    - appdirs==1.4.4
    - arrow==1.1.0
    - astropy==4.0.1.post1
    - atomicwrites==1.3.0
    - attrs==19.3.0
    - autopep8==1.5
    - babel==2.8.0
    - backcall==0.1.0
    - bcrypt==3.1.7
    - binaryornot==0.4.4
    - black==20.8b1
    - bleach==3.1.4
    - cachetools==4.0.0
    - cffi==1.14.0
    - chardet==3.0.4
    - click==7.1.2
    - cloudpickle==1.3.0
    - cookiecutter==1.7.2
    - cryptography==2.8
    - cycler==0.10.0
    - cython==0.29.20
    - decorator==4.4.2
    - defusedxml==0.6.0
    - diff-match-patch==20181111
    - dipy==1.1.1
    - docker==4.2.2
    - docutils==0.16
    - entrypoints==0.3
    - flake8==3.8.3
    - future==0.18.2
    - google-auth==1.12.0
    - google-auth-oauthlib==0.4.1
    - grpcio==1.27.2
    - h5py==2.10.0
    - hdbscan==0.8.26
    - helpdev==0.6.10
    - idna==2.9
    - imagecodecs==2020.2.18
    - imageio==2.8.0
    - imagesize==1.2.0
    - importlib-metadata==1.5.2
    - inflection==0.5.1
    - intervaltree==3.0.2
    - ipykernel==5.5.3
    - ipython==7.13.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jax==0.2.13
    - jedi==0.17.2
    - jinja2==2.11.1
    - jinja2-time==0.2.0
    - joblib==0.14.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.1
    - jupyter-console==6.1.0
    - jupyter-core==4.6.3
    - keyring==21.2.0
    - kiwisolver==1.1.0
    - markdown==3.2.1
    - markupsafe==1.1.1
    - matplotlib==3.2.1
    - mistune==0.8.4
    - mypy-extensions==0.4.3
    - nbconvert==5.6.1
    - nbformat==5.0.4
    - networkx==2.4
    - nibabel==3.1.1
    - notebook==6.0.3
    - numpy==1.18.2
    - numpydoc==0.9.2
    - oauthlib==3.1.0
    - opencv-python==4.2.0.34
    - opt-einsum==3.3.0
    - packaging==20.3
    - pandas==1.0.3
    - pandocfilters==1.4.2
    - paramiko==2.7.1
    - parso==0.7.0
    - pathspec==0.8.1
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==7.0.0
    - pluggy==0.13.1
    - poyo==0.5.0
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.4
    - protobuf==3.11.3
    - psutil==5.7.0
    - ptyprocess==0.6.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.6.0
    - pycparser==2.20
    - pydocstyle==5.0.2
    - pyflakes==2.2.0
    - pygments==2.6.1
    - pyls-black==0.4.6
    - pyls-spyder==0.3.2
    - pynacl==1.3.0
    - pyparsing==2.4.6
    - pypiwin32==223
    - pyqt5==5.12.3
    - pyqt5-sip==12.7.1
    - pyqtwebengine==5.12.1
    - pyquaternion==0.9.9
    - pyrsistent==0.16.0
    - pyshtools==4.6.2
    - python-dateutil==2.8.1
    - python-jsonrpc-server==0.4.0
    - python-language-server==0.36.2
    - python-lsp-jsonrpc==1.0.0
    - python-lsp-server==1.0.1
    - python-slugify==5.0.0
    - pytorch-lightning==0.7.1
    - pytz==2019.3
    - pywavelets==1.1.1
    - pywin32==227
    - pywin32-ctypes==0.2.0
    - pywinpty==0.5.7
    - pyyaml==5.3.1
    - pyzmq==19.0.0
    - qdarkstyle==3.0.2
    - qstylizer==0.2.0
    - qtawesome==1.0.2
    - qtconsole==5.1.0
    - qtpy==1.9.0
    - rawpy==0.15.0
    - regex==2020.11.13
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rope==0.16.0
    - rsa==4.0
    - rtree==0.9.7
    - scikit-image==0.16.2
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - send2trash==1.5.0
    - snowballstemmer==2.0.0
    - sortedcontainers==2.1.0
    - sphinx==2.4.4
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - spyder==5.0.5
    - spyder-kernels==2.0.5
    - tensorboard==2.2.0
    - tensorboard-plugin-wit==1.6.0.post2
    - terminado==0.8.3
    - test-tube==0.7.5
    - testpath==0.4.4
    - text-unidecode==1.3
    - textdistance==4.2.1
    - three-merge==0.1.1
    - tifffile==2020.2.16
    - tinycss2==1.1.0
    - toml==0.10.2
    - torch==1.4.0
    - torchvision==0.5.0
    - tornado==6.0.4
    - tqdm==4.43.0
    - traitlets==4.3.3
    - typing-extensions==3.7.4.3
    - ujson==4.0.1
    - urllib3==1.25.8
    - watchdog==1.0.1
    - wcwidth==0.1.9
    - webencodings==0.5.1
    - websocket-client==0.57.0
    - werkzeug==1.0.0
    - widgetsnbextension==3.5.1
    - xarray==0.16.0
    - yapf==0.29.0
    - zipp==3.1.0
prefix: C:\Users\Nutzer\Miniconda3\envs\pytorch

